Task 1: Load Data into Pandas and Explore Structure 
Load your cleaned supply chain CSV file into a Pandas DataFrame. 
Write code to: 
•	Import Pandas 
•	Read the CSV file using pd.read_csv() 
•	Display the shape (rows and columns) 
•	Display data types of each column 
•	View the first 10 rows 
•	View the last 5 rows 
•	Get summary statistics using .describe()

In [188]:
import pandas as pd
import csv

# Read the csv file using pd.read_csv
df = pd.read_csv("supply_chain_dataset.csv")

# Display the shape
print(f"The file shape is {df.shape}\n")

# Display the data types
print(f"The data types for the columns are: \n{df.dtypes}\n")

# View the columns
print(df.columns)

The file shape is (3000, 16)

The data types for the columns are:
order_id                     str
order_date                   str
product_category             str
quantity                   int64
unit_price               float64
total_cost               float64
supplier_name                str
supplier_location            str
lead_time_days             int64
warehouse_destination        str
delivery_date                str
actual_delivery_days       int64
delivery_status              str
on_time                      str
product_defects          float64
return_status                str
dtype: object

Index(['order_id', 'order_date', 'product_category', 'quantity', 'unit_price',
       'total_cost', 'supplier_name', 'supplier_location', 'lead_time_days',
       'warehouse_destination', 'delivery_date', 'actual_delivery_days',
       'delivery_status', 'on_time', 'product_defects', 'return_status'],
      dtype='str')

In [189]:
# View the first 10 rows
df.head(10)

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
0,ORD-0001,11/28/2022,Fasteners,94,64.49,6062.06,SupplierE,Mexico,32,Warehouse_3,2022-12-30,32,Delayed,Yes,0.0,No Return
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.08,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.50,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered,Yes,0.0,NaN
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.12,supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered,Yes,0.0,No Return
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.33,supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered,Yes,0.0,No Return
5,ORD-0006,2022-08-27,Motors,24,1214.74,29153.76,Supplier A,USA,10,Warehouse_4,2022-09-06,10,Delayed,Yes,0.0,No Return
6,ORD-0007,2023-10-12,Sensors,24,529.64,12711.36,supplierb,Germany,20,Warehouse_3,2023-10-10,20,Delivered,Yes,0.0,No Return
7,ORD-0008,2023-04-23,Pumps,6,1196.34,7178.04,supplierd,India,26,Warehouse_6,2023-05-19,26,Delivered,Yes,0.0,No Return
8,ORD-0009,01/11/2023,Connectors,55,277.06,15238.30,suppliere,Mexico,24,WH_2,2023-02-04,24,Delivered,Yes,0.0,No Return
9,ORD-0010,2022-09-23,Motors,39,4573.28,178357.92,supplierb,Germany,13,Warehouse_4,2022-10-06,13,Delivered,Yes,NaN,No Return

In [190]:
# View the last five rows
df.tail(5)

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
2995,ORD-2996,2022-08-26,Control Systems,66,2677.05,176685.300000,Supplier A,USA,7,Warehouse_1,2022-09-02,7,Delivered,Yes,0.0,No Return
2996,ORD-2997,2023-07-20,Pumps,16,2865.42,45846.720000,SupplierC,China,34,Warehouse_3,08/23/2023,34,Delivered,Yes,0.0,No Return
2997,ORD-2998,2022-01-31,Control Systems,11,2947.31,32420.410000,suppliera,USA,6,Warehouse_4,2022-02-06,6,Delivered,Yes,0.0,No Return
2998,ORD-2999,2023-02-16,Pumps,12,1932.51,23190.120000,SupplierC,China,41,Warehouse_4,2023-04-10,53,Delivered,No,0.0,No Return
2999,ORD-3000,2022-11-10,Control Systems,27,3293.88,89117.659027,suppliera,USA,18,Warehouse_3,2022-11-28,18,Delivered,Yes,0.0,No Return

In [191]:
# Summary statistics
df.describe()

,quantity,unit_price,total_cost,lead_time_days,actual_delivery_days,product_defects
count,3000.000000,3000.000000,3.000000e+03,3000.000000,3000.000000,2846.000000
mean,32.626667,1758.334397,5.667937e+04,20.424667,22.125667,0.288475
std,31.370134,1328.992629,8.356524e+04,10.218470,11.718460,1.407257
min,5.000000,50.410000,-2.073246e+02,5.000000,5.000000,0.000000
25%,14.000000,467.192500,1.123639e+04,12.000000,12.000000,0.000000
50%,24.000000,1474.195000,3.091119e+04,18.000000,20.000000,0.000000
75%,41.000000,2845.570000,7.068851e+04,28.000000,30.000000,0.000000
max,489.000000,4785.890000,1.720595e+06,53.000000,65.000000,10.000000

Task 2: Access Data Using Indexing 
Practice different ways to access data in your DataFrame. 
Write code to: 
•	Select a single column by name and display its first 10 values 
•	Select multiple columns at once 
•	Get the first 3 rows using .iloc 
•	Get rows 10-20 using .loc or .iloc 
•	Get a specific value by row and column 
•	Get all data for a specific order_id

In [192]:
# Select a single column by name and display its first 10 values
df.loc[0:9, 'product_defects']

0    0.0
1    2.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    NaN
Name: product_defects, dtype: float64

In [193]:
# Select multiple columns at once
df[['supplier_name', 'supplier_location', 'lead_time_days',
       'warehouse_destination', 'delivery_date', 'actual_delivery_days',
       'delivery_status']]

,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status
0,SupplierE,Mexico,32,Warehouse_3,2022-12-30,32,Delayed
1,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered
2,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered
3,supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered
4,supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered
...,...,...,...,...,...,...,...
2995,Supplier A,USA,7,Warehouse_1,2022-09-02,7,Delivered
2996,SupplierC,China,34,Warehouse_3,08/23/2023,34,Delivered
2997,suppliera,USA,6,Warehouse_4,2022-02-06,6,Delivered
2998,SupplierC,China,41,Warehouse_4,2023-04-10,53,Delivered
2999,suppliera,USA,18,Warehouse_3,2022-11-28,18,Delivered

In [194]:
# Get the first 3 rows using iloc
df.iloc[0:3]

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
0,ORD-0001,11/28/2022,Fasteners,94,64.49,6062.06,SupplierE,Mexico,32,Warehouse_3,2022-12-30,32,Delayed,Yes,0.0,No Return
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.08,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.50,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered,Yes,0.0,NaN

In [195]:
# Get rows 10-20 using .loc or .iloc 
df.loc[10:20] # The end step is inclusive
df.iloc[10:21] # The end step is not inclusive

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
10,ORD-0011,2023-12-30,Valves,14,749.01,10486.14,SupplierC,China,32,Warehouse_3,2024-01-31,32,Delivered,Yes,0.0,No Return
11,ORD-0012,2022-06-09,Pumps,21,3218.14,67580.94,Supplier C,China,25,Warehouse_2,07/04/2022,25,Delivered,Yes,0.0,No Return
12,ORD-0013,2022-12-29,Connectors,36,404.92,14577.12,SupplierE,Mexico,25,Warehouse_2,2023-01-23,25,Delivered,Yes,0.0,No Return
13,ORD-0014,2022-04-19,Connectors,19,182.46,3466.74,Supplier E,Mexico,30,Warehouse_2,2022-05-19,30,Delivered,Yes,0.0,No Return
14,ORD-0015,2022-09-23,Fasteners,20,77.43,1548.60,suppliere,Mexico,28,Warehouse_1,2022-10-21,28,Delivered,Yes,0.0,No Return
15,ORD-0016,04/07/2022,Sensors,7,1034.62,7242.34,Supplier C,China,44,Warehouse_3,2022-05-21,44,Delivered,Yes,9.0,Partial Return
16,ORD-0017,2022-08-23,Fasteners,38,104.38,3966.44,Supplier E,Mexico,19,Warehouse_2,2022-09-11,19,Delivered,Yes,0.0,No Return
17,ORD-0018,2022-03-16,Control Systems,27,3664.40,98938.80,SupplierA,USA,8,Warehouse_6,2022-03-24,8,Delivered,Yes,0.0,No Return
18,ORD-0019,2022-11-16,Hydraulics,30,1650.17,49505.10,supplierd,India,32,Warehouse_3,2022-12-23,37,Delivered,No,0.0,No Return
19,ORD-0020,2022-11-12,Hydraulics,7,2281.34,15969.38,Supplier D,India,28,Warehouse_1,2022-12-15,33,Delayed,No,7.0,Full Return
20,ORD-0021,2022-09-27,Sensors,91,901.78,82061.98,SupplierC,China,31,Warehouse_1,2022-10-28,31,Delivered,Yes,0.0,No Return

In [196]:
# Get a specific value by row and column 
df.loc[45, 'product_category']

'Control Systems'

In [197]:
# Get all data for a specific order_id
df[df.loc[:, 'order_id'] == 'ORD-0888']

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
887,ORD-0888,2022-03-30,Sensors,13,1142.34,14850.42,supplierb,Germany,16,Warehouse_1,2022-04-15,16,Delivered,Yes,0.0,No Return

Task 3: Filter Data Based on Conditions 
Write code to answer these questions by filtering: 
•	Show all orders with cost greater than $5000 
•	Show all orders from a specific supplier 
•	Show all delivered orders 
•	Show all orders that were delayed (actual_delivery_days > lead_time_days) 
•	Show all orders from a specific date range 
•	Show orders where quantity is less than 50 
For each filter, display the matching rows and count how many records matched.

In [198]:
# Show all orders with cost greater than $5000
df[df['total_cost'] > 5000]

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
0,ORD-0001,11/28/2022,Fasteners,94,64.49,6062.060000,SupplierE,Mexico,32,Warehouse_3,2022-12-30,32,Delayed,Yes,0.0,No Return
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.500000,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered,Yes,0.0,NaN
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.120000,supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered,Yes,0.0,No Return
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.330000,supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered,Yes,0.0,No Return
5,ORD-0006,2022-08-27,Motors,24,1214.74,29153.760000,Supplier A,USA,10,Warehouse_4,2022-09-06,10,Delayed,Yes,0.0,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,ORD-2996,2022-08-26,Control Systems,66,2677.05,176685.300000,Supplier A,USA,7,Warehouse_1,2022-09-02,7,Delivered,Yes,0.0,No Return
2996,ORD-2997,2023-07-20,Pumps,16,2865.42,45846.720000,SupplierC,China,34,Warehouse_3,08/23/2023,34,Delivered,Yes,0.0,No Return
2997,ORD-2998,2022-01-31,Control Systems,11,2947.31,32420.410000,suppliera,USA,6,Warehouse_4,2022-02-06,6,Delivered,Yes,0.0,No Return
2998,ORD-2999,2023-02-16,Pumps,12,1932.51,23190.120000,SupplierC,China,41,Warehouse_4,2023-04-10,53,Delivered,No,0.0,No Return
2999,ORD-3000,2022-11-10,Control Systems,27,3293.88,89117.659027,suppliera,USA,18,Warehouse_3,2022-11-28,18,Delivered,Yes,0.0,No Return

In [199]:
# Show all orders from a specific supplier
df[df['supplier_name'] == 'Supplier E']

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.080000,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return
13,ORD-0014,2022-04-19,Connectors,19,182.46,3466.740000,Supplier E,Mexico,30,Warehouse_2,2022-05-19,30,Delivered,Yes,0.0,No Return
16,ORD-0017,2022-08-23,Fasteners,38,104.38,3966.440000,Supplier E,Mexico,19,Warehouse_2,2022-09-11,19,Delivered,Yes,0.0,No Return
22,ORD-0023,2022-01-17,Connectors,17,95.49,1623.330000,Supplier E,Mexico,17,Warehouse_5,2022-02-03,17,Cancelled,Yes,0.0,No Return
27,ORD-0028,10/09/2022,Connectors,5,388.83,1944.150000,Supplier E,Mexico,22,Warehouse_2,2022-11-17,39,Delivered,No,0.0,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2960,ORD-2961,2022-04-15,Fasteners,27,208.73,5635.710000,Supplier E,Mexico,26,Warehouse_3,2022-05-11,26,Pendng,Yes,0.0,No Return
2964,ORD-2965,2023-09-22,Connectors,38,101.69,3864.220000,Supplier E,Mexico,25,Warehouse_2,2023-10-17,25,Delivered,Yes,0.0,No Return
2970,ORD-2971,2022-08-15,Connectors,14,258.01,4232.051559,Supplier E,Mexico,28,Warehouse_5,2022-09-12,28,Delivered,Yes,0.0,No Return
2974,ORD-2975,2023-05-31,Fasteners,25,161.59,4039.750000,Supplier E,Mexico,26,Warehouse_2,2023-06-26,26,Delayed,Yes,0.0,No Return
2981,ORD-2982,2023-09-01,Connectors,56,196.06,10979.360000,Supplier E,Mexico,18,Warehouse_1,2023-10-06,35,Delivered,No,NaN,No Return

In [200]:
# Show all delivered orders
df[df['delivery_status'] == 'Delivered']

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.080000,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.500000,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered,Yes,0.0,NaN
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.120000,supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered,Yes,0.0,No Return
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.330000,supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered,Yes,0.0,No Return
6,ORD-0007,2023-10-12,Sensors,24,529.64,12711.360000,supplierb,Germany,20,Warehouse_3,2023-10-10,20,Delivered,Yes,0.0,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,ORD-2996,2022-08-26,Control Systems,66,2677.05,176685.300000,Supplier A,USA,7,Warehouse_1,2022-09-02,7,Delivered,Yes,0.0,No Return
2996,ORD-2997,2023-07-20,Pumps,16,2865.42,45846.720000,SupplierC,China,34,Warehouse_3,08/23/2023,34,Delivered,Yes,0.0,No Return
2997,ORD-2998,2022-01-31,Control Systems,11,2947.31,32420.410000,suppliera,USA,6,Warehouse_4,2022-02-06,6,Delivered,Yes,0.0,No Return
2998,ORD-2999,2023-02-16,Pumps,12,1932.51,23190.120000,SupplierC,China,41,Warehouse_4,2023-04-10,53,Delivered,No,0.0,No Return
2999,ORD-3000,2022-11-10,Control Systems,27,3293.88,89117.659027,suppliera,USA,18,Warehouse_3,2022-11-28,18,Delivered,Yes,0.0,No Return

In [201]:
# Show all orders that were delayed (actual_delivery_days > lead_time_days)
df[df['actual_delivery_days'] > df['lead_time_days']]

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
18,ORD-0019,2022-11-16,Hydraulics,30,1650.17,49505.10000,supplierd,India,32,Warehouse_3,2022-12-23,37,Delivered,No,0.0,No Return
19,ORD-0020,2022-11-12,Hydraulics,7,2281.34,15969.38000,Supplier D,India,28,Warehouse_1,2022-12-15,33,Delayed,No,7.0,Full Return
27,ORD-0028,10/09/2022,Connectors,5,388.83,1944.15000,Supplier E,Mexico,22,Warehouse_2,2022-11-17,39,Delivered,No,0.0,No Return
56,ORD-0057,2023-10-08,Fasteners,7,156.12,335.26683,SupplierE,Mexico,28,WH_4,2023-11-15,38,Delivered,No,0.0,No Return
85,ORD-0086,2023-04-05,Connectors,15,446.93,6703.95000,suppliere,Mexico,15,Warehouse_1,2023-05-05,30,Delivered,No,0.0,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2983,ORD-2984,2022-06-20,Motors,12,1613.89,19366.68000,SupplierB,Germany,12,WH_2,2022-07-06,16,Delivered,No,NaN,NaN
2984,ORD-2985,2023-05-23,Fasteners,69,50.41,3478.29000,suppliere,Mexico,22,Warehouse_1,2023-07-04,42,Delivered,No,0.0,No Return
2985,ORD-2986,2023-04-17,Connectors,30,107.88,2769.07637,suppliere,Mexico,28,Warehouse_5,2023-06-04,48,Delayed,No,0.0,No Return
2990,ORD-2991,2022-07-31,Motors,7,3004.82,21033.74000,supplierb,Germany,11,Warehouse_1,2022-08-25,25,Delivered,No,0.0,No Return
2998,ORD-2999,2023-02-16,Pumps,12,1932.51,23190.12000,SupplierC,China,41,Warehouse_4,2023-04-10,53,Delivered,No,0.0,No Return

In [202]:
# Show all orders from a specific date range
pd.to_datetime(df['order_date'], format='mixed') # Convert datatype to datetime

df.loc[df['order_date'].between('2022-01-01', '2023-01-01')]

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.080000,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.500000,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered,Yes,0.0,NaN
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.120000,supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered,Yes,0.0,No Return
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.330000,supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered,Yes,0.0,No Return
5,ORD-0006,2022-08-27,Motors,24,1214.74,29153.760000,Supplier A,USA,10,Warehouse_4,2022-09-06,10,Delayed,Yes,0.0,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2993,ORD-2994,2022-10-18,Connectors,9,408.54,3676.860000,suppliere,Mexico,25,Warehouse_4,2022-11-12,25,Delayed,Yes,0.0,No Return
2994,ORD-2995,2022-05-23,Sensors,26,812.80,21132.800000,supplierb,Germany,12,Warehouse_3,2022-06-04,12,Delivered,Yes,0.0,No Return
2995,ORD-2996,2022-08-26,Control Systems,66,2677.05,176685.300000,Supplier A,USA,7,Warehouse_1,2022-09-02,7,Delivered,Yes,0.0,No Return
2997,ORD-2998,2022-01-31,Control Systems,11,2947.31,32420.410000,suppliera,USA,6,Warehouse_4,2022-02-06,6,Delivered,Yes,0.0,No Return
2999,ORD-3000,2022-11-10,Control Systems,27,3293.88,89117.659027,suppliera,USA,18,Warehouse_3,2022-11-28,18,Delivered,Yes,0.0,No Return

In [203]:
# Show orders where quantity is less than 50 
df[df['quantity'] < 50]

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.080000,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.500000,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered,Yes,0.0,NaN
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.120000,supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered,Yes,0.0,No Return
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.330000,supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered,Yes,0.0,No Return
5,ORD-0006,2022-08-27,Motors,24,1214.74,29153.760000,Supplier A,USA,10,Warehouse_4,2022-09-06,10,Delayed,Yes,0.0,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,ORD-2995,2022-05-23,Sensors,26,812.80,21132.800000,supplierb,Germany,12,Warehouse_3,2022-06-04,12,Delivered,Yes,0.0,No Return
2996,ORD-2997,2023-07-20,Pumps,16,2865.42,45846.720000,SupplierC,China,34,Warehouse_3,08/23/2023,34,Delivered,Yes,0.0,No Return
2997,ORD-2998,2022-01-31,Control Systems,11,2947.31,32420.410000,suppliera,USA,6,Warehouse_4,2022-02-06,6,Delivered,Yes,0.0,No Return
2998,ORD-2999,2023-02-16,Pumps,12,1932.51,23190.120000,SupplierC,China,41,Warehouse_4,2023-04-10,53,Delivered,No,0.0,No Return
2999,ORD-3000,2022-11-10,Control Systems,27,3293.88,89117.659027,suppliera,USA,18,Warehouse_3,2022-11-28,18,Delivered,Yes,0.0,No Return

Task 4: Create New Columns Through Calculations Create derived columns that combine existing data. 
Write code to: 
•	Create a column for order_profit (cost * quantity * 0.25 for 25% margin) 
•	Create a column for efficiency_score (lead_time / actual_delivery_days) 
•	Create a column for high_value_order (True if cost > average_cost, False otherwise) 
•	Create a column for delay_status ("On Time" or "Delayed" based on actual vs expected delivery) 
•	Display the first 10 rows with these new columns

In [204]:
# Create a column for order_profit (cost * quantity * 0.25 for 25% margin) 
df['order_profit'] = df['total_cost'] * df['quantity'] * 0.25
df['order_profit'].head().round(2)

0    142458.41
1      4904.32
2    337353.12
3    210895.74
4     88362.07
Name: order_profit, dtype: float64

In [205]:
# Create a column for efficiency_score (lead_time / actual_delivery_days)
df['efficiency_score'] = df['lead_time_days'] / df['actual_delivery_days']
df['efficiency_score'].head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: efficiency_score, dtype: float64

In [206]:
# Create a column for high_value_order (True if cost > average_cost, False otherwise)
df['high_value_order'] = df['total_cost'] >  df['total_cost'].mean()
df['high_value_order'].head()

0    False
1    False
2    False
3    False
4    False
Name: high_value_order, dtype: bool

In [207]:
# Create a column for delay_status ("On Time" or "Delayed" based on actual vs expected delivery)
import numpy as np

df['delay_status'] = np.where(df['actual_delivery_days'] <= df['lead_time_days'], 'On_time', 'Delayed')
df['delay_status'].head()

0    On_time
1    On_time
2    On_time
3    On_time
4    On_time
Name: delay_status, dtype: str

In [208]:
df.head(10)

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status,order_profit,efficiency_score,high_value_order,delay_status
0,ORD-0001,11/28/2022,Fasteners,94,64.49,6062.06,SupplierE,Mexico,32,Warehouse_3,2022-12-30,32,Delayed,Yes,0.0,No Return,1.424584e+05,1.0,False,On_time
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.08,Supplier E,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return,4.904320e+03,1.0,False,On_time
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.50,Supplier A,USA,17,Warehouse_1,2022-11-20,17,Delivered,Yes,0.0,NaN,3.373531e+05,1.0,False,On_time
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.12,supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered,Yes,0.0,No Return,2.108957e+05,1.0,False,On_time
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.33,supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered,Yes,0.0,No Return,8.836207e+04,1.0,False,On_time
5,ORD-0006,2022-08-27,Motors,24,1214.74,29153.76,Supplier A,USA,10,Warehouse_4,2022-09-06,10,Delayed,Yes,0.0,No Return,1.749226e+05,1.0,False,On_time
6,ORD-0007,2023-10-12,Sensors,24,529.64,12711.36,supplierb,Germany,20,Warehouse_3,2023-10-10,20,Delivered,Yes,0.0,No Return,7.626816e+04,1.0,False,On_time
7,ORD-0008,2023-04-23,Pumps,6,1196.34,7178.04,supplierd,India,26,Warehouse_6,2023-05-19,26,Delivered,Yes,0.0,No Return,1.076706e+04,1.0,False,On_time
8,ORD-0009,01/11/2023,Connectors,55,277.06,15238.30,suppliere,Mexico,24,WH_2,2023-02-04,24,Delivered,Yes,0.0,No Return,2.095266e+05,1.0,False,On_time
9,ORD-0010,2022-09-23,Motors,39,4573.28,178357.92,supplierb,Germany,13,Warehouse_4,2022-10-06,13,Delivered,Yes,NaN,No Return,1.738990e+06,1.0,True,On_time

Task 5: Merge with Supplier Reference Table 
A supplier reference table (supplier_reference.csv) contains contact and location information for each supplier. Load this table and merge it with your orders data. 
Write code to: 
•	Load the supplier reference table 
•	Perform a merge with your orders DataFrame on supplier_name 
•	Display the merged data with both order information and supplier details 
•	Verify that all suppliers matched correctly 
•	Show what new columns were added from the merge

In [209]:
df_ref = pd.read_csv('supplier_reference.csv')
df_ref.head()

,supplier_name,supplier_location,supplier_contact_person,supplier_phone,supplier_email
0,SupplierA,USA,Michael Thompson,415-7821,michael.thompson@suppliera.com
1,SupplierB,Germany,Anna Keller,221-6394,anna.keller@supplierb.de
2,SupplierC,China,Li Wei,310-4478,li.wei@supplierc.cn
3,SupplierD,India,Rahul Mehta,804-5562,rahul.mehta@supplierd.in
4,SupplierE,Mexico,Carlos Ramirez,998-2719,carlos.ramirez@suppliere.mx

In [210]:
# Perform a merge with your orders DataFrame on supplier_name 
# Standardize the supplier names on both tables
df['supplier_name'] = df['supplier_name'].str.strip().str.replace(' ', '').str.title()
df.supplier_name.unique()

supplier_naming = {
    'Suppliera': 'SupplierA',
    'Supplierb': 'SupplierB',
    'Supplierc': 'SupplierC',
    'Supplierd': 'SupplierD',
    'Suppliere': 'SupplierE'
}
df['supplier_name'] = df['supplier_name'].replace(supplier_naming)
df.supplier_name.unique()

# Merge columns
df_merge = df.merge(df_ref, on='supplier_name', how='left')
df_merge.head()

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location_x,lead_time_days,warehouse_destination,...,product_defects,return_status,order_profit,efficiency_score,high_value_order,delay_status,supplier_location_y,supplier_contact_person,supplier_phone,supplier_email
0,ORD-0001,11/28/2022,Fasteners,94,64.49,6062.06,SupplierE,Mexico,32,Warehouse_3,...,0.0,No Return,142458.4100,1.0,False,On_time,Mexico,Carlos Ramirez,998-2719,carlos.ramirez@suppliere.mx
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.08,SupplierE,Mexico,17,Warehouse_2,...,2.0,Partial Return,4904.3200,1.0,False,On_time,Mexico,Carlos Ramirez,998-2719,carlos.ramirez@suppliere.mx
2,ORD-0003,2022-11-03,Control Systems,25,2159.06,53976.50,SupplierA,USA,17,Warehouse_1,...,0.0,NaN,337353.1250,1.0,False,On_time,USA,Michael Thompson,415-7821,michael.thompson@suppliera.com
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.12,SupplierC,China,36,Warehouse_1,...,0.0,No Return,210895.7400,1.0,False,On_time,China,Li Wei,310-4478,li.wei@supplierc.cn
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.33,SupplierB,Germany,15,Warehouse_6,...,0.0,No Return,88362.0725,1.0,False,On_time,Germany,Anna Keller,221-6394,anna.keller@supplierb.de

In [211]:
new_cols = []
for col in df_merge.columns:
    if col not in df.columns:
        new_cols.append(col)
print(new_cols)

['supplier_location_x', 'supplier_location_y', 'supplier_contact_person', 'supplier_phone', 'supplier_email']

Challenge 1: 
Create a pivot table showing average order cost by supplier and product category. What patterns emerge?

In [212]:
pivot_table = df_merge.pivot_table(values='total_cost',
                                   index='supplier_name',
                                   columns='product_category',
                                   aggfunc='mean').round(2)
pivot_table.head()

product_category,Connectors,Control Systems,Fasteners,Hydraulics,Motors,Pumps,Sensors,Valves
supplier_name,,,,,,,,
SupplierA,NaN,89187.16,NaN,NaN,95224.42,NaN,NaN,NaN
SupplierB,NaN,NaN,NaN,NaN,100277.46,NaN,28568.93,26701.27
SupplierC,NaN,NaN,NaN,NaN,NaN,84223.04,26186.35,28113.59
SupplierD,NaN,NaN,NaN,52401.99,NaN,90794.94,NaN,NaN
SupplierE,9237.37,NaN,4886.05,NaN,NaN,NaN,NaN,NaN

1. All suppliers are specialized i.e no supplier covers all product categories
2. SupplierB has the highest average cost with Motors category
3. SupplierC has the least average cost with Fasteners category

Challenge 2: 
Find the top 10 customers (by total spending). Create a DataFrame with customer_id, total_spending, order_count, and average_order_value.

In [213]:
df_merge.columns

Index(['order_id', 'order_date', 'product_category', 'quantity', 'unit_price',
       'total_cost', 'supplier_name', 'supplier_location_x', 'lead_time_days',
       'warehouse_destination', 'delivery_date', 'actual_delivery_days',
       'delivery_status', 'on_time', 'product_defects', 'return_status',
       'order_profit', 'efficiency_score', 'high_value_order', 'delay_status',
       'supplier_location_y', 'supplier_contact_person', 'supplier_phone',
       'supplier_email'],
      dtype='str')

In [219]:
top_ten_customers = df_merge.groupby('order_id').agg(
    total_spending = ('total_cost', 'sum'),
    order_count = ('order_id', 'count'),
    average_order_value = ('total_cost', 'mean')
).round(2).nlargest(10, 'total_spending').reset_index()

top_ten_customers

   order_id  total_spending  order_count  average_order_value
0  ORD-1585      1720595.40            1           1720595.40
1  ORD-1849      1000681.24            1           1000681.24
2  ORD-2712       991898.31            1            991898.31
3  ORD-2493       807800.07            1            807800.07
4  ORD-2148       765820.16            1            765820.16
5  ORD-1941       736079.52            1            736079.52
6  ORD-1132       681233.08            1            681233.08
7  ORD-2065       606704.67            1            606704.67
8  ORD-1915       573672.05            1            573672.05
9  ORD-0986       566971.16            1            566971.16

Challenge 3: 
Use .groupby() to calculate statistics by supplier: average lead time, average delivery time, on-time delivery rate, total orders. 
Which supplier performs best overall?

In [ ]:
stat_by_supp = df_merge.groupby('supplier_name').agg(
    avg_delivery_time = ('actual_delivery_days', 'mean'),
    avg_lead_time = ('lead_time_days', 'mean'),
    on_time_del_rate = ('on_time', lambda z: (z== 'Yes').mean() * 100),
    total_orders = ('order_id', 'count')
).round(2).nlargest(5, 'total_orders')

stat_by_supp

# SupplierA performs the best because of the following reasons:
# Highest orders(769)
# Fastest average delivery time(10.51 days)
# Highest on time delivery rate(94.28%)
# Shortest average lead time(9.94 days)

,avg_delivery_time,avg_lead_time,on_time_del_rate,total_orders
supplier_name,,,,
SupplierA,10.51,9.94,94.28,769
SupplierB,15.87,14.59,87.41,659
SupplierE,26.17,23.31,74.50,647
SupplierC,36.59,34.56,81.30,492
SupplierD,29.80,27.56,80.14,433