Task 1: Handle Missing Values 
Your dataset has some empty cells. Decide what to do with them. 
Write code to: 
•	Find which columns have missing values 
•	Count how many missing values in each column 
•	For columns with few missing values: fill them (use mean for numbers, most common value for text) 
•	For columns with many missing values: decide if those rows should be removed 
•	Check your work: verify missing values are gone or handled

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("supply_chain_dataset.csv")

# To know the count of missing values for each column
df_isnull = df.isnull().sum()
# print(df_isnull)

# Dropping the missing values because there are many and return status could be misleading
df.dropna(subset=['product_defects', 'return_status'], inplace=True)

# View missing values
print(df.isnull().sum())

order_id                 0
order_date               0
product_category         0
quantity                 0
unit_price               0
total_cost               0
supplier_name            0
supplier_location        0
lead_time_days           0
warehouse_destination    0
delivery_date            0
actual_delivery_days     0
delivery_status          0
on_time                  0
product_defects          0
return_status            0
dtype: int64

Task 2: Convert Data Types 
Make sure all columns are the right type for their data. 
Write code to: 
•	Check the current data type of each column 
•	Convert date columns to datetime (so you can do date calculations) 
•	Convert numeric text (like "1500") to actual numbers 
•	Check your work: print the data types to confirm changes

In [2]:
# Check the data types of each column
print(f"The data types in the dataset are: \n{df.dtypes}")

# Change the data type of the date columns
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed')
df['delivery_date'] = pd.to_datetime(df['delivery_date'], format='mixed')

# To view
print(f"The converted data type for delivery_date column is {df.delivery_date.dtype}")
print(f"The converted data type for order_date column is {df.order_date.dtype}")

# Changing numeric text to actual numbers
# All numerical columns were stored correctly but let's use one to set an example
df['quantity'] = pd.to_numeric(df['quantity'])

# To confirm all data types
print(df.dtypes)

The data types in the dataset are:
order_id                     str
order_date                   str
product_category             str
quantity                   int64
unit_price               float64
total_cost               float64
supplier_name                str
supplier_location            str
lead_time_days             int64
warehouse_destination        str
delivery_date                str
actual_delivery_days       int64
delivery_status              str
on_time                      str
product_defects          float64
return_status                str
dtype: object
The converted data type for delivery_date column is datetime64[us]
The converted data type for order_date column is datetime64[us]
order_id                            str
order_date               datetime64[us]
product_category                    str
quantity                          int64
unit_price                      float64
total_cost                      float64
supplier_name                       str
supplier_location                   str
lead_time_days                    int64
warehouse_destination               str
delivery_date            datetime64[us]
actual_delivery_days              int64
delivery_status                     str
on_time                             str
product_defects                 float64
return_status                       str
dtype: object

Task 3: Create Simple Calculated Columns 
Create new columns by combining or transforming existing data. 
Create these new columns: Column 1: Days to Deliver 
•	Subtract order_date from delivery_date to get number of days 
•	This tells you how long each delivery took Column 2: Order Size Category 
•	If quantity < 50: "Small" 
•	If quantity 50-200: "Medium" 
•	If quantity > 200: "Large" 
•	This groups orders by size Column 3: High Cost Flag 
•	If total_cost > average total_cost: 1 (True) 
•	Otherwise: 0 (False) 
•	This marks expensive orders 
Write code to create all three columns. Display sample data showing the new columns

In [3]:
# Create days_to_deliver column
df['days_to_deliver'] = df['delivery_date'] - df['order_date']
df['days_to_deliver'].dt.days

# Create order_size_category column
def order_size_category(quantity):
    if quantity < 50:
        return 'Small'
    elif quantity <= 200:
        return 'Medium'
    else:
        return 'Large'

df['order_size_category'] = df['quantity'].apply(order_size_category)
df['order_size_category']

# Create high_cost_flag column (To mark expensive orders)
df['high_cost_flag'] = (df['total_cost'] > df['total_cost'].mean()).astype(int)
df['high_cost_flag']

# Display new columns
df[['order_date', 'delivery_date', 'days_to_deliver', 'order_size_category', 'quantity', 'high_cost_flag', 'total_cost' ]]

,order_date,delivery_date,days_to_deliver,order_size_category,quantity,high_cost_flag,total_cost
0,2022-11-28,2022-12-30,32 days,Medium,94,0,6062.060000
1,2022-02-20,2022-03-09,17 days,Small,16,0,1226.080000
3,2022-12-15,2023-01-20,36 days,Small,33,0,25563.120000
4,2022-03-02,2022-03-17,15 days,Small,13,0,27188.330000
5,2022-08-27,2022-09-06,10 days,Small,24,0,29153.760000
...,...,...,...,...,...,...,...
2995,2022-08-26,2022-09-02,7 days,Medium,66,1,176685.300000
2996,2023-07-20,2023-08-23,34 days,Small,16,0,45846.720000
2997,2022-01-31,2022-02-06,6 days,Small,11,0,32420.410000
2998,2023-02-16,2023-04-10,53 days,Small,12,0,23190.120000
2999,2022-11-10,2022-11-28,18 days,Small,27,1,89117.659027

Task 4: Clean Up Text Data 
Text data is often messy. Clean it so it's consistent. 
Write code to: 
•	Remove extra spaces from supplier_name and product_category 
•	Make all supplier_name values the same capitalization (all uppercase or title case) 
•	Check for spelling inconsistencies (like "Motor" vs "Moter") and fix any you find 
•	Display before and after to verify cleaning worked

In [4]:
# Removing extra spaces from supplier_name and product_category
print(f'Before cleaning: {df.head(10)}')
# df[['supplier_name', 'product_category']].head(10)

df['supplier_name'] = df['supplier_name'].str.strip()
df['supplier_name'] = df['supplier_name'].str.replace(' ','')
df['product_category'] = df['product_category'].str.strip()

# Standardization
df['supplier_name'] = df['supplier_name'].str.title()
df['product_category'] = df['product_category'].str.title()

# Checking inconsistencies
df['supplier_name'].values.unique()
df['product_category'].values.unique()

# After cleaning
print('After cleaning: ')
df.head(15)

Before cleaning:     order_id order_date product_category  quantity  unit_price  total_cost  \
0   ORD-0001 2022-11-28        Fasteners        94       64.49     6062.06
1   ORD-0002 2022-02-20        Fasteners        16       76.63     1226.08
3   ORD-0004 2022-12-15           Valves        33      774.64    25563.12
4   ORD-0005 2022-03-02           Motors        13     2091.41    27188.33
5   ORD-0006 2022-08-27           Motors        24     1214.74    29153.76
6   ORD-0007 2023-10-12          Sensors        24      529.64    12711.36
7   ORD-0008 2023-04-23            Pumps         6     1196.34     7178.04
8   ORD-0009 2023-01-11       Connectors        55      277.06    15238.30
10  ORD-0011 2023-12-30           Valves        14      749.01    10486.14
11  ORD-0012 2022-06-09            Pumps        21     3218.14    67580.94

   supplier_name supplier_location  lead_time_days warehouse_destination  \
0      SupplierE            Mexico              32           Warehouse_3
1     Supplier E            Mexico              17           Warehouse_2
3      supplierc             China              36           Warehouse_1
4      supplierb           Germany              15           Warehouse_6
5     Supplier A               USA              10           Warehouse_4
6      supplierb           Germany              20           Warehouse_3
7      supplierd             India              26           Warehouse_6
8      suppliere            Mexico              24                  WH_2
10     SupplierC             China              32           Warehouse_3
11    Supplier C             China              25           Warehouse_2

   delivery_date  actual_delivery_days delivery_status on_time  \
0     2022-12-30                    32         Delayed     Yes
1     2022-03-09                    17       Delivered     Yes
3     2023-01-20                    36       Delivered     Yes
4     2022-03-17                    15       Delivered     Yes
5     2022-09-06                    10         Delayed     Yes
6     2023-10-10                    20       Delivered     Yes
7     2023-05-19                    26       Delivered     Yes
8     2023-02-04                    24       Delivered     Yes
10    2024-01-31                    32       Delivered     Yes
11    2022-07-04                    25       Delivered     Yes

    product_defects   return_status days_to_deliver order_size_category  \
0               0.0       No Return         32 days              Medium
1               2.0  Partial Return         17 days               Small
3               0.0       No Return         36 days               Small
4               0.0       No Return         15 days               Small
5               0.0       No Return         10 days               Small
6               0.0       No Return         -2 days               Small
7               0.0       No Return         26 days               Small
8               0.0       No Return         24 days              Medium
10              0.0       No Return         32 days               Small
11              0.0       No Return         25 days               Small

    high_cost_flag
0                0
1                0
3                0
4                0
5                0
6                0
7                0
8                0
10               0
11               1
After cleaning:

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,delivery_date,actual_delivery_days,delivery_status,on_time,product_defects,return_status,days_to_deliver,order_size_category,high_cost_flag
0,ORD-0001,2022-11-28,Fasteners,94,64.49,6062.06,Suppliere,Mexico,32,Warehouse_3,2022-12-30,32,Delayed,Yes,0.0,No Return,32 days,Medium,0
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.08,Suppliere,Mexico,17,Warehouse_2,2022-03-09,17,Delivered,Yes,2.0,Partial Return,17 days,Small,0
3,ORD-0004,2022-12-15,Valves,33,774.64,25563.12,Supplierc,China,36,Warehouse_1,2023-01-20,36,Delivered,Yes,0.0,No Return,36 days,Small,0
4,ORD-0005,2022-03-02,Motors,13,2091.41,27188.33,Supplierb,Germany,15,Warehouse_6,2022-03-17,15,Delivered,Yes,0.0,No Return,15 days,Small,0
5,ORD-0006,2022-08-27,Motors,24,1214.74,29153.76,Suppliera,USA,10,Warehouse_4,2022-09-06,10,Delayed,Yes,0.0,No Return,10 days,Small,0
6,ORD-0007,2023-10-12,Sensors,24,529.64,12711.36,Supplierb,Germany,20,Warehouse_3,2023-10-10,20,Delivered,Yes,0.0,No Return,-2 days,Small,0
7,ORD-0008,2023-04-23,Pumps,6,1196.34,7178.04,Supplierd,India,26,Warehouse_6,2023-05-19,26,Delivered,Yes,0.0,No Return,26 days,Small,0
8,ORD-0009,2023-01-11,Connectors,55,277.06,15238.30,Suppliere,Mexico,24,WH_2,2023-02-04,24,Delivered,Yes,0.0,No Return,24 days,Medium,0
10,ORD-0011,2023-12-30,Valves,14,749.01,10486.14,Supplierc,China,32,Warehouse_3,2024-01-31,32,Delivered,Yes,0.0,No Return,32 days,Small,0
11,ORD-0012,2022-06-09,Pumps,21,3218.14,67580.94,Supplierc,China,25,Warehouse_2,2022-07-04,25,Delivered,Yes,0.0,No Return,25 days,Small,1
12,ORD-0013,2022-12-29,Connectors,36,404.92,14577.12,Suppliere,Mexico,25,Warehouse_2,2023-01-23,25,Delivered,Yes,0.0,No Return,25 days,Small,0
13,ORD-0014,2022-04-19,Connectors,19,182.46,3466.74,Suppliere,Mexico,30,Warehouse_2,2022-05-19,30,Delivered,Yes,0.0,No Return,30 days,Small,0
14,ORD-0015,2022-09-23,Fasteners,20,77.43,1548.60,Suppliere,Mexico,28,Warehouse_1,2022-10-21,28,Delivered,Yes,0.0,No Return,28 days,Small,0
15,ORD-0016,2022-04-07,Sensors,7,1034.62,7242.34,Supplierc,China,44,Warehouse_3,2022-05-21,44,Delivered,Yes,9.0,Partial Return,44 days,Small,0
16,ORD-0017,2022-08-23,Fasteners,38,104.38,3966.44,Suppliere,Mexico,19,Warehouse_2,2022-09-11,19,Delivered,Yes,0.0,No Return,19 days,Small,0

Task 5: Create Performance Metrics 
Create columns that show how well things performed. 
Create these columns: 
Column 1: On Time (1 or 0) 
•	If days_to_deliver <= lead_time_days: 1 (on time) 
•	Otherwise: 0 (late) 
•	This flags the orders that arrived on schedule Column 2: Cost Per Unit 
•	Divide total_cost by quantity 
•	This shows the unit price 
•	Helps compare if one order was more expensive per item 
Column 3: Supplier Performance Grade 
•	For each supplier, calculate their on-time delivery rate 
•	Merge this back to each order 
•	This shows each supplier's overall reliability 
Write code to create all three. Display orders with their performance metrics.

In [8]:
# Extract days from the time delta values for days_to_deliver
# df['days_to_deliver'] = df['days_to_deliver'].dt.days

# Create an on_time_num column
df['on_time_num'] = (df['days_to_deliver'] <= df['lead_time_days']).astype(int)

# Create a cost_per_unit column
df['cost_per_unit'] = df['total_cost'] / df['quantity']

# Create a supplier_perf_grade column
supp_perf =  df.groupby('supplier_name')['on_time_num'].mean().reset_index()
supp_perf.columns = ['supplier_name', 'supplier_on_time_num_rate']
# Merge columns
df = df.merge(supp_perf, on='supplier_name', how='left')
# df.drop('supplier_on_time_rate')
df.head(10)

,order_id,order_date,product_category,quantity,unit_price,total_cost,supplier_name,supplier_location,lead_time_days,warehouse_destination,...,delivery_status,on_time,product_defects,return_status,days_to_deliver,order_size_category,high_cost_flag,on_time_num,cost_per_unit,supplier_on_time_num_rate
0,ORD-0001,2022-11-28,Fasteners,94,64.49,6062.06,Suppliere,Mexico,32,Warehouse_3,...,Delayed,Yes,0.0,No Return,32,Medium,0,1,64.49,0.758562
1,ORD-0002,2022-02-20,Fasteners,16,76.63,1226.08,Suppliere,Mexico,17,Warehouse_2,...,Delivered,Yes,2.0,Partial Return,17,Small,0,1,76.63,0.758562
2,ORD-0004,2022-12-15,Valves,33,774.64,25563.12,Supplierc,China,36,Warehouse_1,...,Delivered,Yes,0.0,No Return,36,Small,0,1,774.64,0.830357
3,ORD-0005,2022-03-02,Motors,13,2091.41,27188.33,Supplierb,Germany,15,Warehouse_6,...,Delivered,Yes,0.0,No Return,15,Small,0,1,2091.41,0.895270
4,ORD-0006,2022-08-27,Motors,24,1214.74,29153.76,Suppliera,USA,10,Warehouse_4,...,Delayed,Yes,0.0,No Return,10,Small,0,1,1214.74,0.951220
5,ORD-0007,2023-10-12,Sensors,24,529.64,12711.36,Supplierb,Germany,20,Warehouse_3,...,Delivered,Yes,0.0,No Return,-2,Small,0,1,529.64,0.895270
6,ORD-0008,2023-04-23,Pumps,6,1196.34,7178.04,Supplierd,India,26,Warehouse_6,...,Delivered,Yes,0.0,No Return,26,Small,0,1,1196.34,0.797927
7,ORD-0009,2023-01-11,Connectors,55,277.06,15238.30,Suppliere,Mexico,24,WH_2,...,Delivered,Yes,0.0,No Return,24,Medium,0,1,277.06,0.758562
8,ORD-0011,2023-12-30,Valves,14,749.01,10486.14,Supplierc,China,32,Warehouse_3,...,Delivered,Yes,0.0,No Return,32,Small,0,1,749.01,0.830357
9,ORD-0012,2022-06-09,Pumps,21,3218.14,67580.94,Supplierc,China,25,Warehouse_2,...,Delivered,Yes,0.0,No Return,25,Small,1,1,3218.14,0.830357

Challenge 1: 
Create a "Delivery Speed Category" column: "Fast" (< 7 days), "Normal" (7-21 days), "Slow" (> 21 days). How many orders fall into each category?

In [ ]:
# Create a delivery_speed_cat column
def del_speed_cat(days):
    if days < 7:
        return 'Fast'
    elif days <= 21:
        return 'Normal'
    else:
        return 'Slow'
df['delivery_speed_cat'] = df['days_to_deliver'].apply(del_speed_cat)
df['delivery_speed_cat'].value_counts().unique

<bound method Series.unique of delivery_speed_cat
Normal    1293
Slow      1268
Fast       146
Name: count, dtype: int64>

Challenge 2: 
Create a column showing how old each order is (days since order_date). Are older orders treated differently than newer ones?

In [ ]:
# To get the order age in days
df['order_age_days'] = (pd.Timestamp.today() - df['order_date']).dt.days
df['order_age_days'].head(10)

# Compare total_cost 
# df.groupby('order_age_days')['total_cost'].mean().round(2).head(15)

print(df[['order_age_days', 'total_cost']].corr()) # No relationship btw the two

                order_age_days  total_cost
order_age_days        1.000000    0.010613
total_cost            0.010613    1.000000
                order_age_days  on_time_num
order_age_days        1.000000    -0.004998
on_time_num          -0.004998     1.000000

Challenge 3: 
For each product_category, calculate the average cost. Then create a column showing if each order's cost is above or below the category average.

In [26]:
# Compare average cost and product_category
category_avg = df.groupby('product_category')['total_cost'].transform('mean')

# Attach categorical data to ascertain whether total cost is above or below category average
df['category_avg'] = np.where(df['total_cost'] > category_avg, 'Above', 'Below')

# Display the columns
df[['total_cost', 'product_category', 'category_avg']]

         total_cost product_category category_avg
0       6062.060000        Fasteners        Above
1       1226.080000        Fasteners        Below
2      25563.120000           Valves        Below
3      27188.330000           Motors        Below
4      29153.760000           Motors        Below
...             ...              ...          ...
2702  176685.300000  Control Systems        Above
2703   45846.720000            Pumps        Below
2704   32420.410000  Control Systems        Below
2705   23190.120000            Pumps        Below
2706   89117.659027  Control Systems        Below

[2707 rows x 3 columns]

In [35]:
df.head(20)
df['supplier_on_time_num_rate'] = df['supplier_on_time_num_rate'].round(2)
df['total_cost'] = df['total_cost'].round(2)
df['cost_per_unit'] = df['cost_per_unit'].round(2)

In [36]:
# To save this cleaned dataset
df.to_csv('supply_chain_cleaned_dataset.csv', index=False)